// GENERATED by `pnpm -F @sonasky/feeds-def gen` - do not edit by hand.
// Re-run after changing customFeeds.ts's `customFeedDefs`.

export const customFeedRkeys: Record<string, string> = {
  __test_feed__: "dafd530d03accb7a",
};
