/**
 * Regenerates src/catalog.generated.ts - the frozen feed record-key catalog.
 *
 * The rkey is sha256(seed) truncated to 16 hex chars (raw label ids can't be
 * record keys: some trip the PDS slur filter). Hashing happens here, once, in
 * Node, so the shipped catalog is plain data that also loads in the browser.
 *
 * Run after changing @sonasky/labels-def:  pnpm -F @sonasky/feeds-def gen
 */

import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { getAllLabels } from "@sonasky/labels-def";
import {
  ALL_USERS_INTERACTED_SEED,
  ALL_USERS_SEED,
  ALL_USERS_TRENDING_SEED,
  SPECIES_TRENDING_SEED_SUFFIX,
} from "./const.ts";
import { englishName, truncateGraphemes } from "./displayName.ts";
import type { GeneratedCatalog } from "./index.ts";

const rkey = (seed: string): string => createHash("sha256").update(seed).digest("hex").slice(0, 16);

const catalog: GeneratedCatalog = {
  allRkey: rkey(ALL_USERS_SEED),
  allTrendingRkey: rkey(ALL_USERS_TRENDING_SEED),
  allInteractedRkey: rkey(ALL_USERS_INTERACTED_SEED),
  // Only labels that are earned by liking a post get feeds; meta labels without
  // a `post` (e.g. sonasky-ref-sheet-user) are skipped.
  labels: getAllLabels()
    .filter((label) => label.post !== undefined)
    .map((label) => {
      const speciesName = englishName(label) || label.id;
      return {
        labelId: label.id,
        speciesName,
        displayName: truncateGraphemes(`🕔 ${speciesName}`),
        trendingDisplayName: truncateGraphemes(`📈 ${speciesName}`),
        feedRkey: rkey(label.id),
        trendingRkey: rkey(`${label.id}${SPECIES_TRENDING_SEED_SUFFIX}`),
      };
    }),
};

const out = fileURLToPath(new URL("./catalog.generated.ts", import.meta.url));
const body =
  "// GENERATED by `pnpm -F @sonasky/feeds-def gen` - do not edit by hand.\n" +
  "// Re-run after changing @sonasky/labels-def.\n\n" +
  'import type { GeneratedCatalog } from "./index.ts";\n\n' +
  `export const generatedCatalog: GeneratedCatalog = ${JSON.stringify(catalog, null, 2)};\n`;

writeFileSync(out, body);
console.log(`Wrote ${catalog.labels.length + 3} feed keys to ${out}`);
