/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "app.sonasky.ref";

type $nsid = typeof $nsid;

export { $nsid };

/** Record containing a user's character. */
type Main = {
  $type: "app.sonasky.ref";

  /**
   * Timestamp when the actor first created the record.
   */
  createdAt: l.DatetimeString;

  /**
   * Timestamp when the actor modified the record.
   */
  modifiedAt?: l.DatetimeString;

  /**
   * Character details.
   */
  character?: l.LexMap;
};

export type { Main };

/** Record containing a user's character. */
const main = /*#__PURE__*/ l.record<"tid", Main>(
  "tid",
  $nsid,
  /*#__PURE__*/ l.object({
    createdAt: /*#__PURE__*/ l.string({ format: "datetime" }),
    modifiedAt: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: "datetime" })),
    character: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.lexMap()),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
