/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "app.sonasky.ref.asset";

type $nsid = typeof $nsid;

export { $nsid };

/** A standalone image asset uploaded directly to the user's repo, for use as a character ref sheet when no existing Bluesky post is available. */
type Main = {
  $type: "app.sonasky.ref.asset";

  /**
   * The uploaded image blob.
   */
  image: l.BlobRef;

  /**
   * Alt text for the image.
   */
  alt?: string;

  /**
   * Timestamp when the asset was uploaded.
   */
  createdAt: l.DatetimeString;
};

export type { Main };

/** A standalone image asset uploaded directly to the user's repo, for use as a character ref sheet when no existing Bluesky post is available. */
const main = /*#__PURE__*/ l.record<"tid", Main>(
  "tid",
  $nsid,
  /*#__PURE__*/ l.object({
    image: /*#__PURE__*/ l.blob({
      accept: ["image/png", "image/jpeg", "image/webp", "image/gif"],
      maxSize: 5000000,
    }),
    alt: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 2000 })),
    createdAt: /*#__PURE__*/ l.string({ format: "datetime" }),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
