/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "app.sonasky.ref.galleryImage";

type $nsid = typeof $nsid;

export { $nsid };

/** An additional art piece of a character, sourced from a Bluesky post or an uploaded asset. */
type Main = {
  $type: "app.sonasky.ref.galleryImage";

  /**
   * The rkey of the app.sonasky.ref character record this image belongs to.
   */
  characterRkey: string;

  /**
   * AT-URI of the source Bluesky post or app.sonasky.ref.asset record containing the image.
   */
  source: l.AtUriString;

  /**
   * Index of the image within the source record's image array.
   */
  sourceImageIndex?: number;

  /**
   * Credit for the artist who created this piece.
   */
  artist: string;

  /**
   * Optional title for the piece.
   */
  title?: string;

  /**
   * Alt text for the image.
   */
  alt?: string;

  /**
   * Whether this image is NSFW.
   */
  nsfw?: boolean;

  /**
   * Timestamp when the gallery image was added.
   */
  createdAt: l.DatetimeString;
};

export type { Main };

/** An additional art piece of a character, sourced from a Bluesky post or an uploaded asset. */
const main = /*#__PURE__*/ l.record<"tid", Main>(
  "tid",
  $nsid,
  /*#__PURE__*/ l.object({
    characterRkey: /*#__PURE__*/ l.string({ maxLength: 512 }),
    source: /*#__PURE__*/ l.string({ format: "at-uri" }),
    sourceImageIndex: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.integer({ minimum: 0 }), 0),
    ),
    artist: /*#__PURE__*/ l.string({ maxLength: 256 }),
    title: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 128 })),
    alt: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 2000 })),
    nsfw: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.boolean(), false)),
    createdAt: /*#__PURE__*/ l.string({ format: "datetime" }),
  }),
);

export { main };

const $type = $nsid;

type $type = typeof $type;

export { $type };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main);
export const $build = /*#__PURE__*/ main.build.bind(main);
export const $assert = /*#__PURE__*/ main.assert.bind(main);
export const $check = /*#__PURE__*/ main.check.bind(main);
export const $cast = /*#__PURE__*/ main.cast.bind(main);
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main);
export const $matches = /*#__PURE__*/ main.matches.bind(main);
export const $parse = /*#__PURE__*/ main.parse.bind(main);
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
export const $validate = /*#__PURE__*/ main.validate.bind(main);
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
